load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "click_to_spin",
    srcs = ["click_to_spin.cc"],
    linkopts = ["-lglut", "-lGLU", "-lGL"]    
)

cc_binary(
    name = "polygon",
    srcs = ["polygon.cc"],
    linkopts = ["-lglut", "-lGLU", "-lGL"]      
)